{% set name = "mistral-common" %}
{% set version = "1.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mistral_common-{{ version }}.tar.gz
    sha256: 550583d70a395c3586cfb748ffab53bd1d7c3409507f0efc0118bff30ffb26e9
  - url: https://raw.githubusercontent.com/mistralai/mistral-common/v{{ version }}/LICENCE
    sha256: 5ed6f79e77734b5a60740dd821af5ecac9a6f33709c860eea4e20fcb6cca7fcc
    fn: LICENSE


build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  # pyproject.toml currently limits the python version to less than 3.14
  skip: true  # [py<310 or py>313]

requirements:
  host:
    - pip
    - python
    - wheel
    # setuptools must be at least this version for compatibility with PEP639. The pyproject.toml
    # for mistral-common looks to be defined with this PEP in mind, so setuptools needs
    # to support it as well. 
    # https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license-and-license-files
    - setuptools >=77.0.3
  run:
    - python
    - pydantic >=2.7,<3.0
    - jsonschema >=4.21.1
    
    - typing-extensions >=4.11.0
    - tiktoken >=0.7.0
    - pillow >=10.3.0
    - requests >=2.0.0
    - numpy >=1.25
    - pydantic-extra-types >=2.10.5
    # pydantic-extra-types[pycountry]
    - pycountry >=23
  run_constrained:
    - sentencepiece >=0.2.0
    - opencv >=4.0.0
    - opencv-python-headless >=4.0.0
    - soundfile >=0.12.1
    - soxr-python >=0.5.0
    - huggingface-hub >=0.32.4
    - fastapi >=0.115.12
    - pydantic-settings >=2.9.1
    - click >=8.1.0

test:
  imports:
    - mistral_common
    - mistral_common.protocol
    - mistral_common.tokens
    - mistral_common.protocol.instruct
    - mistral_common.tokens.tokenizers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mistralai/mistral-common
  summary: Set of tools to help you work with Mistral models
  description: |
    Set of tools to help you work with Mistral models.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  dev_url: https://github.com/mistralai/mistral-common
  doc_url: https://github.com/mistralai/mistral-common

extra:
  recipe-maintainers:
    - jeongseok-meta
